### ISSUE TITLE
Performance issue with one rule on one file

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1754]
**Describe the bug**
In a small-ish code base this took about 4 **minutes**:
```
semgrep --error --config https://semgrep.dev/p/r2c
```

But by removing a single file, the same run took only 8 **seconds** total:
```
semgrep --error --config https://semgrep.dev/p/r2c --exclude entitlement.js
```

Running semgrep with a `-v` allowed me to find the single specific rule that was causing the performance issue:
```
javascript.jsonwebtoken.security.audit.jwt-decode-without-verify.jwt-decode-without-verify
```
Interesting points:

1. The problematic file is a generated file, not hand-written. It is about 1M in size, so much larger than a typical JavaScript file.

2. This JS file actually has nothing to do with JWTs, but it does define a handful of functions called `decode()` which seems to be the focus of the problematic rule.

3. This problematic rule is rather complex and has a lot of `not`'s, so it is not surprising that there are edge cases that would cause exponential runtime. That said, I am surprised because the first set of clauses (under `pattern-either`) all need `require('jsonwebtoken')` and that never occurs in entitlement.js at all. So this would suggest that if no pattern matches from `pattern-either` there could be short-circuiting all the rest of the `pattern-not-inside`s.

4. Just for comparison, this alternate rule set ran on all files--including entitlement.js--just fine, taking about 14 seconds:
```
semgrep --error --config https://semgrep.dev/p/r2c-ci
```

**To Reproduce**
Not at liberty to share the whole file, but the generated `decode()` functions look like this, with varying amounts of items in the switch statement:
```
                      UpsertProductRequest.decode = function decode(reader, length) {
                        if (!(reader instanceof $Reader))
                            reader = $Reader.create(reader);
                        var end = length === undefined ? reader.len : reader.pos + length, message = new $UpsertProductRequest();
                        while (reader.pos < end) {
                            var tag = reader.uint32();
                            switch (tag >>> 3) {
                            case 1:
                                message.name = reader.string();
                                break;
                            case 2:
                                message.displayName = reader.string();
                                break;
                            case 3:
                                message.type = reader.string();
                                break;

                            default:
                                reader.skipType(tag & 7);
                                break;
                            }
                        }
                        return message;
                    };
```

**Expected behavior**
No single rule should overwhelm the system.

**Comment by aryx** [comment]
I think I've fixed that today: https://github.com/returntocorp/semgrep/pull/1750
If you use the very latest, you should get a parse error after 5s instead of trying forever to parse the file.

**Comment by aryx** [comment]
hmm, actually it's another problem.

**Comment by aryx** [comment]
BTW there's a --timeout option to semgrep to avoid slowing down everything for pathological files

**Comment by aryx** [comment]
cc @mjambon for performance issue.

**Comment by mschwager** [comment]
Hi @msorens,

We've made quite a few performance improvements in Semgrep [`0.34.0`](https://github.com/returntocorp/semgrep/blob/develop/CHANGELOG.md#0340---2020-12-09). Can you confirm that you're still seeing performance issues on this file with the latest version of Semgrep?

**Comment by msorens** [comment]
Thanks for the note, @mschwager ! Here is some data that I just ran--**v 0.33.0**:

```
 $ time semgrep --error --config https://semgrep.dev/p/r2c
ran 78 rules on 254 files: 3 findings

real	0m44.956s
user	0m46.433s
sys	0m5.067s

$ time semgrep --error --config https://semgrep.dev/p/r2c --exclude entitlement.js
excluding files:
- entitlement.js
ran 78 rules on 253 files: 3 findings

real	0m12.079s
user	0m14.314s
sys	0m4.479s
```
I then upgrade to **0.34.0** and re-ran:
```
 $ time semgrep --error --config https://semgrep.dev/p/r2c
ran 78 rules on 254 files: 3 findings

real	0m46.339s
user	0m46.991s
sys	0m5.117s

$ time semgrep --error --config https://semgrep.dev/p/r2c --exclude entitlement.js
excluding files:
- entitlement.js
ran 78 rules on 253 files: 3 findings

real	0m11.879s
user	0m14.514s
sys	0m4.420s
```

My conclusions: 
(1) There were indeed performance improvements--but not from 0.34.0--the results for 0.33.0 and 0.34.0 were essentially identical for my data.
(2) There is still a substantial performance penalty (about 4x slower) for the single file I targeted.
(3) The results for 0.33.0 and 0.34.0 are substantially better than in my initial report from September 30 (looks like I failed to note the version at that time).

**Comment by mschwager** [comment]
Complex rules on large files will undoubtedly incur a performance cost. I'm trying to get a feel for what a "fix" looks like here. What are your performance expectations in this situation? If performance is a primary concern over correctness, can `--exclude`, `--timeout`, and/or `--timeout-threshold` achieve the desired outcome? Or would you rather remove the offending rule instead of file?

**Comment by msorens** [comment]
Ah, guess I did not directly address that. I am satisfied with the current performance level, given the improvements already in place. An extra 30 seconds for an occasional unwieldy file is not a concern for me.

**Comment by mschwager** [comment]
> Ah, guess I did not directly address that. I am satisfied with the current performance level, given the improvements already in place. An extra 30 seconds for an occasional unwieldy file is not a concern for me.

Great! We're currently putting a lot of effort into performance improvements, so this should get even better shortly.

With all the different code <-> rule combinations out there it's often difficult for us to foresee all degenerative cases, so thanks for pointing us the right direction. I'm going to close this one out, feel free to open new issues if you see particularly bad performance on a rule:file combination :+1:
