### ISSUE TITLE
Too liberal matching for Solidity's try-catch construct

### ISSUE THREAD

**Issue by wuestholz** [semgrep/semgrep#6052]
**Describe the bug**

It seems like there is something off with how semgrep matches external calls in Solidity's try-catch construct.

**To Reproduce**

I wrote the following rule to reproduce this against the the develop-branch:

```yml
rules:
  - id: test-try-catch
    message: Found two calls to function bar().
    languages:
      - solidity
    severity: WARNING
    patterns:
      - pattern: |
          function foo(...) {
            ...
            try this.bar(...) {
              ...
            } catch {
              ...
            }
            ...
            this.bar(...);
            ...
          }
```

Semgrep emits a match for the following Solidity code:
```Solidity
pragma solidity 0.8.16;

contract C {
  function bar() external { }
  function foo() external returns (uint256 r) {
    r = 0;
    try this.bar() {
      r += 2;
    } catch {
      r += 3;
    }
    return r;
  }
}
```

However, there is only a single call to function `bar()` in function `foo()`.

**Expected behavior**
I expect the above rule not to result in a match for the above Solidity code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
develop-branch via docker:

```
docker run --rm -v "${PWD}:/src" returntocorp/semgrep:develop semgrep scan --config issue.yml issue.sol
```

**Use case**
Building rules for detecting security-critical issues in Solidity code

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1854/too-liberal-matching-for-soliditys-try-catch-construct. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
This should be fixed by #6040

**Comment by aryx** [comment]
Or maybe there's something else going on.

**Comment by aryx** [comment]
seems related to #6031

**Comment by wuestholz** [comment]
@aryx Thanks! I think this is a separate issue. I used Docker and the develop-branch to verify that this is still happening after the fix in https://github.com/returntocorp/semgrep/pull/6040.

**Comment by wuestholz** [comment]
@aryx I just checked if I can still reproduce this issue in the current semgrep playground (see https://semgrep.dev/playground/s/ONE7). Unfortunately, I'm still seeing the same unexpected behavior. Any idea what might be causing this?

**Comment by wuestholz** [comment]
@aryx I just checked if I can still reproduce this issue in the current semgrep playground (see https://semgrep.dev/s/oQ0X). I improved the example code slightly to explain the semantics of try-catch below:

```solidity
pragma solidity 0.8.17;

contract C {
  function bar() external { /* require(false); */ }
  function foo() external returns (uint256) {
    uint256 r = 1;
    try this.bar() {
      r *= 2;
    } catch {
      r *= 3;
    }
    r *= 5;
    return r;
  }
}
```

Unfortunately, I'm still seeing the same unexpected behavior.

I tried to look at the parts of the parser that seem to deal with try-catch constructs (https://github.com/returntocorp/semgrep/blob/c31b3ca3d6ff0345b0db8ed79f8e484be4324299/languages/solidity/generic/Parse_solidity_tree_sitter.ml#L2024-L2055), but I can't quite make sense of it. Especially the comment at the top makes me wonder if there is a slight misunderstanding regarding the semantics of try-catch constructs in Solidity.

The semantics is to execute the call `this.bar()` and then to execute the try-block if the call doesn't fail. Otherwise the catch-block gets executed. For instance, in the code above the return value of `foo()` should be 10. If we were to uncomment the require-statement in `bar()` the return value of `foo()` would be 15. Does this match the comment and the implementation in the parser?

**Comment by wuestholz** [comment]
I just checked if I can still reproduce this issue in the current semgrep playground (see https://semgrep.dev/s/oQ0X). Unfortunately, I'm still seeing the same unexpected behavior. Any idea what might be causing this?

**Comment by wuestholz** [comment]
I tried to further minimize the rule and the corresponding code (see https://semgrep.dev/playground/s/AbgBw). I still don't understand why there is a match given that there is just a single call to `bar()` in the following code:

```Solidity
pragma solidity 0.8.17;

contract C {
  function bar() external { /* require(false); */ }
  function foo() external returns (uint256) {
    uint256 r = 1;
    try this.bar() {
      r *= 2;
    } catch {
      r *= 3;
    }
    return 5 * r;
  }
}
```

**Comment by wuestholz** [comment]
Looks like this behavior is not even specific to Solidity. I observe the same issue for Java (see https://semgrep.dev/playground/s/BYgD6).

**Comment by wuestholz** [comment]
In case this helps, here's another Java example that doesn't even use the try-catch construct: https://semgrep.dev/playground/s/DbL0y.
